### ISSUE TITLE
Isnt this supposed to be realtime *clock* ?

### ISSUE THREAD

**Issue by vjoao** [fedberry/fedberry-config#27]
https://github.com/fedberry/fedberry-config/blob/38f1a76df77428b53b51008d861d05ac4ee21407/fedberry-config#L1464

It reads "realtime cock" LOL

**Comment by agrez** [comment]
Hah! That's what makes us so unique... no other distro has this particular feature ;-)
https://github.com/fedberry/fedberry-config/commit/8ae125edf04cd5941005fe31d80f4998e24cfc07
